version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE=admin: surveys
    networks:
      - node-api-network

  api:
    container_name: api-container
    image: node:16
    restart: always
    working_dir: /usr/home/app
    command: bash -c "npm install && npm run debug"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - PORT=5050
      - MONGO_URL=mongodb://root:example@mongo:27017
    volumes:
      - ./dist/:/usr/home/app/dist/
      - ./package.json:/usr/home/app/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    networks:
      - node-api-network

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#    networks:
#      - node-api-network

networks:
  node-api-network:
    driver: bridge
